### ISSUE TITLE
Find Kobweb colors if they are subclass instances

### ISSUE THREAD

**Issue by bitspittle** [varabyte/kobweb-intellij-plugin#41]
This causes an issue:

```kotlin
interface ColorScheme {
    val _50: Color
    val _100: Color
   ...
}

object ColorSchemes {
    /** A color scheme which ranges from near white (_50) to near black (_900). */
    val Monochrome = object : ColorScheme {
        override val _50 = Color.rgb(0XF2F2F2)
        override val _100 = Color.rgb(0XE6E6E6)
        ...
   }
}
```

because a user would expect `ColorSchemes.Monochrome._100` to show the color in the gutter but it doesn't, because our code is finding a reference to the "_100" in the base interface instead.

---

To repro:

* In a tmp directory somewhere: `$ kobweb create app`
* Open `Index.kt`
* Scroll down to the button, where we have lines like `ColorSchemes.Monochrome._600`

Expected: 

Color shows up in gutter

What happens:

Color does not show up in the gutter

**Comment by Nxllpointer** [comment]
Huh weird. The algorithm should be able to trace that back. I can take a look at this tomorrow if you don't want to

**Comment by Nxllpointer** [comment]
@bitspittle Hm i dont think we can do a whole lot about this on the plugin side, since this seems to be a core issue with Intellij's reference system. I assume, that intellij is unable to find the declarations, because the silk library creates anonymous objects. You could try changing the anonymous objects to just regular objects though. I dont see any downside of this and it should be API-compatible.

So 
```kt
val Monochrome = object : ColorScheme
```
becomes
```kt
object Monochrome : ColorScheme
```

**Comment by bitspittle** [comment]
Will update all anonymous objects to non-anonymous ones. Looks like that's working!

Closing this bug as otherwise non-actionable. Thanks for looking into it.
